/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main()
	{
		System.out.println("hello");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
    
    public int addInts(int a, int b) {
    	return a+b;
    }
    
}
